title: Oluwatobi Aduloju # your name (or website title) here
logo: "/images/profile-pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Oluwatobi is a business/data analyst who has extensive experience in understanding data needs and can weave together a complex and sophistically oriented solution
 to the data needs based on a comprehensive understanding of the various computation processes;  
 including research. He can contribute significantly to a company’s sustainable growth and possesses a good team spirit.
 
 <br>
 <br>
 
  <a href="https://www.linkedin.com/in/aduloju-oluwatobi/">View my LinkedIn Profile</a> 

