title: Oluwatobi Aduloju # your name (or website title) here
logo: "/images/tobi-modified.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Oluwatobi is a business/data analyst, who has extensive experience in understanding sophisticated client needs and is able to weave together complex,<br> 
  sophistically- oriented solution: with proven skills <br>
  to guarantee success in any given tasks.<br>
  A proven and capable business analyst who can identify customer’s <br>
  needs and contribute to company’s sustainable growth, with a
  comprehensive understanding of various computation processes
  including research and possess a good team spirit.
  <a href="https://www.linkedin.com/in/aduloju-oluwatobi/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
