title: Oluwatobi Aduloju # your name (or website title) here
logo: "/images/tobi-modified.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Oluwatobi is a business/data analyst who has extensive experience in understanding data needs and can weave together a complex, sophistically oriented solution with a comprehensive understanding of the various computation processes;  including research. He can contribute significantly to a company’s sustainable growth and possesses a good team spirit.
  <a href="https://www.linkedin.com/in/aduloju-oluwatobi/">View my LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
